// Checks every checked-in 2v2 template against the hard rules and sensible quality thresholds.

package main

import (
	"bytes"
	"fmt"
	"github.com/stretchr/testify/assert"
	"os"
	"path/filepath"
	"testing"
)

const (
	templatesDir   = "../../schedules"
	minTeamsTested = 6
	maxTeamsTested = 14
	minMatchesTest = 4
	maxMatchesTest = 10
)

func readTemplate(t *testing.T, numTeams, matchesPerTeam int) []Row {
	file, err := os.Open(filepath.Join(templatesDir, fmt.Sprintf("2p_%d_%d.csv", numTeams, matchesPerTeam)))
	if !assert.Nil(t, err) {
		return nil
	}
	defer file.Close()
	rows, err := ReadCsv(file)
	assert.Nil(t, err)
	return rows
}

func TestTemplatesCoverEveryShape(t *testing.T) {
	// There must be no stray files and no gaps, since BuildRandomSchedule fails on a missing template.
	files, err := filepath.Glob(filepath.Join(templatesDir, "2p_*.csv"))
	assert.Nil(t, err)
	assert.Equal(t, (maxTeamsTested-minTeamsTested+1)*(maxMatchesTest-minMatchesTest+1), len(files))
}

func TestTemplatesHardRules(t *testing.T) {
	for numTeams := minTeamsTested; numTeams <= maxTeamsTested; numTeams++ {
		for matchesPerTeam := minMatchesTest; matchesPerTeam <= maxMatchesTest; matchesPerTeam++ {
			rows := readTemplate(t, numTeams, matchesPerTeam)
			err := Validate(rows, numTeams, matchesPerTeam)
			assert.Nil(t, err, "%d teams, %d matches per team", numTeams, matchesPerTeam)
		}
	}
}

// The thresholds are what the checked-in templates achieve, rounded to what is worth defending. Small events can't
// do better: with few teams a pair has to meet again and a team has to play soon after its last match.
func TestTemplatesQuality(t *testing.T) {
	for numTeams := minTeamsTested; numTeams <= maxTeamsTested; numTeams++ {
		for matchesPerTeam := minMatchesTest; matchesPerTeam <= maxMatchesTest; matchesPerTeam++ {
			rows := readTemplate(t, numTeams, matchesPerTeam)
			metrics := Measure(rows, numTeams)
			partnerBound, opponentBound := Bounds(numTeams, matchesPerTeam)
			message := fmt.Sprintf("%d teams, %d matches per team: %+v", numTeams, matchesPerTeam, metrics)

			assert.LessOrEqual(t, metrics.MaxPartner, partnerBound+1, message)
			assert.LessOrEqual(t, metrics.MaxOpponent, opponentBound+2, message)
			assert.LessOrEqual(t, metrics.MaxStationDiff, 1, message)
			assert.LessOrEqual(t, metrics.MaxRedBlueDiff, 1, message)

			// Spacing: no back-to-back matches except a few in small events, and at least one match between a
			// team's own at 14 teams.
			if numTeams >= 9 {
				assert.LessOrEqual(t, metrics.BackToBack, 5, message)
			}
			if numTeams >= 10 {
				assert.LessOrEqual(t, metrics.BackToBack, 2, message)
			}
			if numTeams >= 14 {
				assert.GreaterOrEqual(t, metrics.MinBetween, 1, message)
			}
		}
	}
}

func TestCheckedInTemplatesMatchGenerator(t *testing.T) {
	// A few shapes, including the 14-team one M-Ayhem uses, so the generator and the checked-in files can't drift
	// apart unnoticed. Rerun the generator after changing it.
	for _, shape := range [][2]int{{6, 4}, {9, 5}, {12, 6}, {14, 8}} {
		numTeams, matchesPerTeam := shape[0], shape[1]
		var generated bytes.Buffer
		rows := Generate(numTeams, matchesPerTeam, seedFor(numTeams, matchesPerTeam))
		assert.Nil(t, WriteCsv(&generated, rows))
		checkedIn, err := os.ReadFile(
			filepath.Join(templatesDir, fmt.Sprintf("2p_%d_%d.csv", numTeams, matchesPerTeam)),
		)
		assert.Nil(t, err)
		assert.Equal(t, string(checkedIn), generated.String(), "%d teams, %d matches per team", numTeams, matchesPerTeam)
	}
}

func TestValidateRejectsBrokenTemplates(t *testing.T) {
	// 6 teams x 1 match = 6 appearances: two matches with two surrogates.
	rows := []Row{
		{{1, false}, {2, false}, {3, false}, {4, false}},
		{{5, false}, {6, false}, {1, true}, {2, true}},
	}
	assert.Nil(t, Validate(rows, 6, 1))

	repeated := []Row{rows[0], {{5, false}, {6, false}, {5, true}, {2, true}}}
	assert.NotNil(t, Validate(repeated, 6, 1), "a team twice in a match")

	missing := []Row{rows[0], {{5, false}, {5, true}, {1, true}, {2, true}}}
	assert.NotNil(t, Validate(missing, 6, 1), "a team never plays")

	doubleSurrogate := []Row{
		{{1, false}, {2, false}, {3, false}, {4, false}},
		{{5, false}, {6, false}, {1, true}, {2, true}},
		{{1, true}, {3, true}, {4, true}, {2, true}},
	}
	assert.NotNil(t, Validate(doubleSurrogate, 6, 1))
}

func TestCsvRoundTrip(t *testing.T) {
	rows := []Row{{{1, false}, {2, true}, {3, false}, {4, false}}}
	var buffer bytes.Buffer
	assert.Nil(t, WriteCsv(&buffer, rows))
	assert.Equal(t, "1,0,2,1,0,0,3,0,4,0,0,0\n", buffer.String())
	read, err := ReadCsv(&buffer)
	assert.Nil(t, err)
	assert.Equal(t, rows, read)

	_, err = ReadCsv(bytes.NewBufferString("1,0,2,0,3,0,4,0,5,0,6,0\n"))
	assert.NotNil(t, err, "third slots must be empty")
}
