// Copyright 2020 Team 254. All Rights Reserved.
// Author: pat@patfairbank.com (Patrick Fairbank)
//
// Model of a game-specific rule.

package game

type Rule struct {
	Id             int
	RuleNumber     string
	IsMajor        bool
	IsRankingPoint bool
	Description    string
}

// All fouls the referee may assess, generated by hand from the table in specs/RULES.md and must match it; a test checks
// this. Rules that the referee may assess at either severity (G423, MA2615) appear twice, since the rule dropdown is
// filtered by the foul's type. Card-only rules and the no-score rule MA2622 are not listed. Ids must stay stable,
// because stored fouls refer to them.
// @formatter:off
var rules = []*Rule{
	{1, "G210", true, false, "Do not force another robot to commit a foul."},
	{2, "G401", true, false, "DRIVE TEAM members must be behind the lines during AUTO and"},
	{3, "G402", true, false, "DRIVE TEAM members must not control their robots during auton, directly or through operator console, unless it’s for a-stop or e-stop"},
	{4, "G403", false, false, "Do not cross the midfield line into the opponents half during AUTO."},
	{5, "G408", true, false, "Neither a Human or Human Player may damage a Scoring Element"},
	{6, "G415", true, false, "Contacting another robot inside the robot’s perimeter [Stackable with taking a piece within a robots bounding box (re: yellow card)]"},
	{7, "G423", false, false, "This isn’t combat robotics. A ROBOT may not damage or functionally impair an opponent ROBOT: A. deliberately. B. regardless of intent, by initiating contact, either directly or transitively via a SCORING ELEMENT CONTROLLED by the ROBOT, inside the vertical projection of an opponent’s ROBOT PERIMETER. Damage or functional impairment because of contact with a tipped-over opponent ROBOT, which is not perceived by a referee to be deliberate, is not a violation of this rule."},
	{8, "G423", true, false, "This isn’t combat robotics. A ROBOT may not damage or functionally impair an opponent ROBOT: A. deliberately. B. regardless of intent, by initiating contact, either directly or transitively via a SCORING ELEMENT CONTROLLED by the ROBOT, inside the vertical projection of an opponent’s ROBOT PERIMETER. Damage or functional impairment because of contact with a tipped-over opponent ROBOT, which is not perceived by a referee to be deliberate, is not a violation of this rule."},
	{9, "G424", true, false, "Attaching, entangling or tipping over another robot intentionally"},
	{10, "G425", false, false, "Pinning a robot for longer than 3 seconds"},
	{11, "G429", true, false, "Drive team members must stay designated areas"},
	{12, "G430", true, false, "Robot should only be operated by Drivers"},
	{13, "G434", true, false, "Coaches many not touch Scoring Elements, unless for safety purposes"},
	{14, "MA2601", true, true, "Contacting the opposing team's balance beam at during the endgame [Ref Discretion, Can stack with MA2602]. This results in an automatic endgame RP for the other team, no matter the scoring"},
	{15, "MA2602", true, true, "Contacting the opposing team AT ALL while they’re in their own Balance Beam during the endgame [Can stack with MA2601]. This results in an automatic endgame RP for the other team, no matter the scoring."},
	{16, "MA2603", true, true, "Going into another team's safe house or safe zone within auton. This also results in an automatic auto RP for the other team, no matter the scoring."},
	{17, "MA2604", true, false, "No Hoarding: More than 6 non-scoring treasures in your safe house or safe zone. Major Foul is given at the beginning of infraction, given every 10 seconds 6 non-scoring treasures are in the safe house or safe zone."},
	{18, "MA2606", false, false, "Entering another alliance’s Human Player Loading zone, Safe House, Safe Zone, or touching the balance beam before endgame. This can be reapplied every 10 seconds if contact does not end. Exception: Ref may allow an exception due to momentary contact with the balance beam or contact due to contact with another robot (e.g. being pushed into the balance beam). Exception: The Apron facing the middle of the field is okay to touch during anytime before the endgame. Note that MA2601 applies during endgame."},
	{19, "MA2607", false, false, "Placing/Throwing a treasure into the field not through the Human Player Loading holes [doesn’t apply during the “toss”, may be escalated by the head ref if flagrant]"},
	{20, "MA2608", false, false, "Placing/Throwing a treasure that bounces not first on the same alliance’s robot, or the Human Player Loading zone Floor."},
	{21, "MA2609", false, false, "Contacting scoring own shelf repeatedly or in an unsafe manner [Ref Discretion]"},
	{22, "MA2610", false, false, "Starting with over 1 piece during auton. The robot is also ineligible to gain points within auton by scoring in the shelf"},
	{23, "MA2611", false, false, "Descoring pieces from other teams [can stack with MA2620]"},
	{24, "MA2612", false, false, "Robot deliberately permanently destroying a treasure"},
	{25, "MA2613", false, false, "Adding treasures within endgame [treasure does not count for scoring]"},
	{26, "MA2614", false, false, "Placing/Shooting treasures within the opposing alliance zones"},
	{27, "MA2615", false, false, "Failure to obey ref area signs"},
	{28, "MA2615", true, false, "Failure to obey ref area signs"},
	{29, "MA2616", false, false, "Controlling more than 2 gamepieces at a non-momentarily time [additional treasures do not count for scoring][ref discretion]"},
	{30, "MA2617", false, false, "Throwing a treasure into/on the shelf not inside own Safe House[treasure does not count for scoring]"},
	{31, "Damaging contact", true, false, "Initiating damaging contact [Ref discretion]"},
	{32, "Reaching onto field", true, false, "Having a part of your body reaching on to the field [Ref Discretion]"},
}

// @formatter:on
var ruleMap map[int]*Rule

// Returns the rule having the given ID, or nil if no such rule exists.
func GetRuleById(id int) *Rule {
	return GetAllRules()[id]
}

// Returns a slice of all defined rules that carry point penalties.
func GetAllRules() map[int]*Rule {
	if ruleMap == nil {
		ruleMap = make(map[int]*Rule, len(rules))
		for _, rule := range rules {
			ruleMap[rule.Id] = rule
		}
	}
	return ruleMap
}
